# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 040eb4bf4d12b22792bf3ef1cdd1305abc54eea67803ab35fd0d3836d20371dcf6fd6391a2ae54c076215b8ca0f69c1354d5e8db4a7c93b9501ed7e04a844062

test:
  secret_key_base: bf94b544871ae0f495c1fd84a9df88bfd52215cb2695e9e2539d435a336fbb40654191c1875723fdf405e9e9537efa6c493da5b35677b46887672a0595a2dd69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
